spring:
    datasource:
        driver-class-name:  org.postgresql.Driver
        url: jdbc:postgresql://localhost:5432/postgres
        username: postgres
        password: root
        platform: postgres

    jpa:
        hibernate:
            ddl-auto: update
            show-sql: true
            dialect: org.hibernate.dialect.PostgreSQLDialect
